# Generated by Django 5.2.11 on 2026-02-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Administrator'), ('HR_MANAGER', 'HR Manager'), ('HR_OFFICER', 'HR Officer'), ('LINE_MANAGER', 'Line Manager'), ('PVC', 'Pro Vice Chancellor'), ('ADMIN_OFFICER', 'Administration Officer'), ('FINANCE_OFFICER', 'Finance Officer'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=32),
        ),
        migrations.AlterField(
            model_name='userinvite',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Administrator'), ('HR_MANAGER', 'HR Manager'), ('HR_OFFICER', 'HR Officer'), ('LINE_MANAGER', 'Line Manager'), ('PVC', 'Pro Vice Chancellor'), ('ADMIN_OFFICER', 'Administration Officer'), ('FINANCE_OFFICER', 'Finance Officer'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=32),
        ),
    ]
