# Generated by Django 5.2.11 on 2026-02-14 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('dataset', models.CharField(choices=[('EMPLOYEES', 'Employees'), ('EMPLOYMENT_HISTORY', 'Employment History'), ('LEAVE_REQUESTS', 'Leave Requests'), ('LEAVE_BALANCES', 'Leave Balances'), ('VACANCIES', 'Vacancies'), ('APPLICANTS', 'Applicants'), ('APPRAISALS', 'Appraisals'), ('TRAINING_RECORDS', 'Training Records'), ('ESTABLISHMENT', 'Staff Establishment'), ('SEPARATIONS', 'Separations')], max_length=40)),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'dataset', 'created_by')},
            },
        ),
    ]
