version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-hris}
      POSTGRES_USER: ${POSTGRES_USER:-hris}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-hris}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-hris}:${POSTGRES_PASSWORD:-hris}@db:5432/${POSTGRES_DB:-hris}
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./backend:/app
      - media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: [ "/app/entrypoint.sh" ]

  celery_worker:
    build:
      context: ./backend
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-hris}:${POSTGRES_PASSWORD:-hris}@db:5432/${POSTGRES_DB:-hris}
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    command: celery -A config worker -l INFO

  celery_beat:
    build:
      context: ./backend
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-hris}:${POSTGRES_PASSWORD:-hris}@db:5432/${POSTGRES_DB:-hris}
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    command: celery -A config beat -l INFO

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_BASE_URL: "https://hris.zchpc.ac.zw"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: [ "npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173" ]

volumes:
  pgdata:
  media:
