# Generated by Django 5.2.11 on 2026-03-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('FIXED_TERM', 'Fixed Term'), ('PART_TIME', 'Part time'), ('CASUAL', 'Casual'), ('CONSULTANCY', 'Consultancy')], default='PERMANENT', max_length=40),
        ),
    ]
