# Generated by Django 5.2.11 on 2026-02-19 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_alter_employeedocument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationAssistancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_children_per_employee', models.PositiveIntegerField(default=2)),
                ('allowed_levels', models.JSONField(blank=True, default=list)),
                ('max_claim_amount_per_child', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('frequency', models.CharField(choices=[('TERM', 'Per Term'), ('SEMESTER', 'Per Semester'), ('YEAR', 'Per Year')], default='TERM', max_length=20)),
                ('eligible_contract_types', models.JSONField(blank=True, default=list)),
                ('require_completed_probation', models.BooleanField(default=False)),
                ('max_child_age', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Education Assistance Policy',
                'verbose_name_plural': 'Education Assistance Policies',
            },
        ),
        migrations.CreateModel(
            name='Dependant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('date_of_birth', models.DateField()),
                ('relationship', models.CharField(choices=[('CHILD', 'Child'), ('OTHER', 'Other')], default='CHILD', max_length=20)),
                ('education_level', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('TERTIARY', 'Tertiary')], default='PRIMARY', max_length=20)),
                ('institution_name', models.CharField(blank=True, max_length=160)),
                ('student_number', models.CharField(blank=True, max_length=80)),
                ('benefit_eligible', models.BooleanField(default=True)),
                ('ineligible_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependants', to='employees.employee')),
            ],
            options={
                'ordering': ['employee', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DependantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('BIRTH_CERTIFICATE', 'Birth certificate'), ('OTHER', 'Other')], max_length=40)),
                ('encrypted_file', models.FileField(upload_to='benefits/dependants/')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dependant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='benefits.dependant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveIntegerField()),
                ('period_type', models.CharField(choices=[('TERM', 'Term'), ('SEMESTER', 'Semester'), ('YEAR', 'Year')], max_length=20)),
                ('period_label', models.CharField(max_length=40)),
                ('institution_name', models.CharField(max_length=160)),
                ('amount_claimed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('NEEDS_INFO', 'Needs additional documents'), ('HR_REJECTED', 'Rejected by HR'), ('FINANCE_PENDING', 'Pending Accounts/Finance'), ('PAID', 'Paid')], default='SUBMITTED', max_length=20)),
                ('hr_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_note', models.TextField(blank=True)),
                ('finance_processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dependant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='education_claims', to='benefits.dependant')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_claims', to='employees.employee')),
                ('finance_processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_processed_education_claims', to=settings.AUTH_USER_MODEL)),
                ('hr_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_reviewed_education_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationClaimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('INVOICE', 'Invoice/Receipt'), ('REGISTRATION', 'Proof of registration'), ('PAYMENT_PROOF', 'Proof of payment'), ('OTHER', 'Other')], max_length=40)),
                ('encrypted_file', models.FileField(upload_to='benefits/claims/')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='benefits.educationclaim')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='educationclaim',
            constraint=models.UniqueConstraint(fields=('dependant', 'academic_year', 'period_type', 'period_label'), name='uniq_claim_child_period'),
        ),
    ]
