# Generated by Django 5.2.11 on 2026-03-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependant',
            name='relationship',
            field=models.CharField(choices=[('CHILD', 'Child'), ('SPOUSE', 'Spouse'), ('FATHER', 'Father'), ('MOTHER', 'Mother'), ('OTHER', 'Other')], default='CHILD', max_length=20),
        ),
    ]
