# Generated by Django 5.2.11 on 2026-02-14 00:00

from django.db import migrations, models


def seed_defaults(apps, schema_editor):
    ApprovalProcessConfig = apps.get_model('governance', 'ApprovalProcessConfig')

    defaults = [
        {
            "process_code": "LEAVE_LINE_MANAGER",
            "name": "Leave: Line Manager Approval",
            "description": "Roles allowed to approve leave at line manager stage.",
            "allowed_roles": ["LINE_MANAGER", "SYSTEM_ADMIN"],
            "is_active": True,
        },
        {
            "process_code": "LEAVE_HR",
            "name": "Leave: HR Approval",
            "description": "Roles allowed to approve leave at HR stage.",
            "allowed_roles": ["HR_MANAGER", "HR_OFFICER", "SYSTEM_ADMIN"],
            "is_active": True,
        },
        {
            "process_code": "VACANCY_APPROVAL",
            "name": "Recruitment: Vacancy Approval",
            "description": "Roles allowed to approve a vacancy.",
            "allowed_roles": ["HR_MANAGER", "SYSTEM_ADMIN"],
            "is_active": True,
        },
        {
            "process_code": "VACANCY_PUBLISH",
            "name": "Recruitment: Vacancy Publish",
            "description": "Roles allowed to publish a vacancy.",
            "allowed_roles": ["HR_MANAGER", "HR_OFFICER", "SYSTEM_ADMIN"],
            "is_active": True,
        },
    ]

    for row in defaults:
        ApprovalProcessConfig.objects.update_or_create(process_code=row["process_code"], defaults=row)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ApprovalProcessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_code', models.CharField(choices=[('LEAVE_LINE_MANAGER', 'Leave: Line Manager Approval'), ('LEAVE_HR', 'Leave: HR Approval'), ('VACANCY_APPROVAL', 'Recruitment: Vacancy Approval'), ('VACANCY_PUBLISH', 'Recruitment: Vacancy Publish')], max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(seed_defaults, migrations.RunPython.noop),
    ]
