# Generated by Django 5.2.11 on 2026-02-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalprocessconfig',
            name='process_code',
            field=models.CharField(choices=[('LEAVE_LINE_MANAGER', 'Leave: Line Manager Approval'), ('LEAVE_HR', 'Leave: HR Approval'), ('LEAVE_PVC', 'Leave: PVC Approval'), ('LEAVE_ADMIN', 'Leave: Admin Approval'), ('LEAVE_FINANCE', 'Leave: Finance Approval'), ('EDUCATION_CLAIM_HR', 'Education Assistance: HR Approval'), ('EDUCATION_CLAIM_FINANCE', 'Education Assistance: Finance Payment'), ('VACANCY_APPROVAL', 'Recruitment: Vacancy Approval'), ('VACANCY_PUBLISH', 'Recruitment: Vacancy Publish')], max_length=40, unique=True),
        ),
    ]
