# Generated by Django 5.2.11 on 2026-02-11 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('schema', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('period', models.CharField(default='ANNUAL', max_length=40)),
                ('self_assessment', models.JSONField(blank=True, default=dict)),
                ('supervisor_feedback', models.JSONField(blank=True, default=dict)),
                ('hr_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('SUPERVISOR_REVIEW', 'Supervisor Review'), ('HR_REVIEW', 'HR Review'), ('FINALIZED', 'Finalized')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='employees.employee')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appraisals', to='performance.appraisaltemplate')),
            ],
            options={
                'unique_together': {('employee', 'template', 'year', 'period')},
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('progress_note', models.TextField(blank=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='performance.appraisal')),
            ],
        ),
    ]
