# Generated by Django 5.2.11 on 2026-02-19 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('EMPLOYEES', 'Employees'), ('LEAVE_BALANCES', 'Leave balances'), ('CONTRACTS', 'Contracts')], max_length=40)),
                ('upload', models.FileField(upload_to='imports/')),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PREVIEWED', 'Previewed'), ('COMMITTED', 'Committed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('preview_rows', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
