# Generated by Django 5.2.11 on 2026-02-14 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('budgeted_headcount', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establishment_items', to='employees.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establishment_items', to='employees.position')),
            ],
            options={
                'unique_together': {('year', 'department', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Separation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('separation_date', models.DateField()),
                ('separation_type', models.CharField(choices=[('RESIGNATION', 'Resignation'), ('RETIREMENT', 'Retirement'), ('TERMINATION', 'Termination'), ('CONTRACT_END', 'Contract End'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separations', to='employees.employee')),
            ],
        ),
    ]
