# Generated by Django 5.2.11 on 2026-02-19

import os
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _map_category(raw: str) -> str:
    """
    Best-effort mapping from legacy doc_type strings to the new Category enum.
    Falls back to CV if unknown.
    """
    if not raw:
        return "CV"
    s = raw.strip().lower()

    # direct matches (common)
    direct = {
        "national id/passport": "NATIONAL_ID_OR_PASSPORT",
        "national id": "NATIONAL_ID_OR_PASSPORT",
        "passport": "NATIONAL_ID_OR_PASSPORT",
        "academic certificates": "ACADEMIC_CERTIFICATES",
        "academic certificate": "ACADEMIC_CERTIFICATES",
        "professional certifications": "PROFESSIONAL_CERTIFICATIONS",
        "professional certification": "PROFESSIONAL_CERTIFICATIONS",
        "cv": "CV",
        "resume": "CV",
        "banking details": "BANKING_DETAILS",
        "bank details": "BANKING_DETAILS",
    }
    if s in direct:
        return direct[s]

    # fuzzy contains
    if any(k in s for k in ["passport", "national", " id", "id "]):
        return "NATIONAL_ID_OR_PASSPORT"
    if any(k in s for k in ["academic", "degree", "diploma", "transcript", "certificate"]):
        return "ACADEMIC_CERTIFICATES"
    if any(k in s for k in ["professional", "certification", "license", "licence"]):
        return "PROFESSIONAL_CERTIFICATIONS"
    if any(k in s for k in ["bank", "account", "branch"]):
        return "BANKING_DETAILS"
    if any(k in s for k in ["cv", "resume", "résumé"]):
        return "CV"

    return "CV"


def forwards(apps, schema_editor):
    EmployeeDocument = apps.get_model("employees", "EmployeeDocument")

    # Fill new fields for existing rows (non-blocking best effort)
    for doc in EmployeeDocument.objects.all():
        # category might contain legacy values after rename from doc_type
        doc.category = _map_category(getattr(doc, "category", None))

        if not getattr(doc, "original_name", ""):
            try:
                doc.original_name = os.path.basename(doc.encrypted_file.name) or "legacy_document"
            except Exception:
                doc.original_name = "legacy_document"

        # content_type can remain blank
        if getattr(doc, "content_type", None) is None:
            doc.content_type = ""

        # size_bytes best effort
        if not getattr(doc, "size_bytes", 0):
            try:
                doc.size_bytes = doc.encrypted_file.size or 0
            except Exception:
                doc.size_bytes = 0

        # versioning defaults
        if not getattr(doc, "version", None):
            doc.version = 1
        if getattr(doc, "is_latest", None) is None:
            doc.is_latest = True

        doc.save(
            update_fields=[
                "category",
                "original_name",
                "content_type",
                "size_bytes",
                "version",
                "is_latest",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employmenthistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # rename old fields so existing data is preserved
        migrations.RenameField(
            model_name="employeedocument",
            old_name="file",
            new_name="encrypted_file",
        ),
        migrations.RenameField(
            model_name="employeedocument",
            old_name="doc_type",
            new_name="category",
        ),

        # add new metadata/versioning fields with safe defaults
        migrations.AddField(
            model_name="employeedocument",
            name="original_name",
            field=models.CharField(default="", blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="content_type",
            field=models.CharField(default="", blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="size_bytes",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="is_latest",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        # optional: keep choices & default in migration state too (not DB-enforced)
        migrations.AlterField(
            model_name="employeedocument",
            name="category",
            field=models.CharField(
                choices=[
                    ("NATIONAL_ID_OR_PASSPORT", "National ID/Passport"),
                    ("ACADEMIC_CERTIFICATES", "Academic Certificates"),
                    ("PROFESSIONAL_CERTIFICATIONS", "Professional Certifications"),
                    ("CV", "CV"),
                    ("BANKING_DETAILS", "Banking Details"),
                ],
                default="CV",
                max_length=60,
            ),
        ),

        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
