# Generated by Django 5.2.11 on 2026-02-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employeedocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='retirement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
