# Generated by Django 5.2.11 on 2026-02-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_retirement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='category',
            field=models.CharField(choices=[('NATIONAL_ID_OR_PASSPORT', 'National ID/Passport'), ('ACADEMIC_CERTIFICATES', 'Academic Certificates'), ('PROFESSIONAL_CERTIFICATIONS', 'Professional Certifications'), ('CV', 'CV'), ('BANKING_DETAILS', 'Banking Details'), ('OTHER', 'Other')], default='CV', max_length=60),
        ),
    ]
