# Generated by Django 5.2.11 on 2026-03-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employeedocument_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='school',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.CharField(blank=True, choices=[('MR', 'Mr'), ('MS', 'Ms'), ('MRS', 'Mrs'), ('DR', 'Dr'), ('PROF', 'Prof'), ('REV', 'Rev')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('FIXED_TERM', 'Fixed Term'), ('PART_TIME', 'Part time'), ('CASUAL', 'Casual'), ('CONSULTANCY', 'Consultancy')], default='PERMANENT', max_length=40),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='contract_type',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('FIXED_TERM', 'Fixed Term'), ('PART_TIME', 'Part time'), ('CASUAL', 'Casual'), ('CONSULTANCY', 'Consultancy')], max_length=40),
        ),
    ]
