# Generated by Django 5.2.11 on 2026-02-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0002_leaverequest_admin_officer_leaverequest_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='carry_forward_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
