# Generated by Django 5.2.11 on 2026-03-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0003_leavetype_carry_forward_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='leave_docs/'),
        ),
    ]
